name: b2t
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.9.0=py311h459d7ec_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.5.0=py311h06a4308_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py311h06a4308_0
  - audioread=3.0.1=py311h38be061_1
  - aws-c-auth=0.7.7=h4faf3ed_1
  - aws-c-cal=0.6.9=h3b91eb8_1
  - aws-c-common=0.9.8=hd590300_0
  - aws-c-compression=0.2.17=hfd9eb17_6
  - aws-c-event-stream=0.3.2=h1fff966_7
  - aws-c-http=0.7.14=hc86c171_2
  - aws-c-io=0.13.36=hc23c90e_0
  - aws-c-mqtt=0.9.10=hba57965_1
  - aws-c-s3=0.4.1=hfadff92_0
  - aws-c-sdkutils=0.1.12=hfd9eb17_5
  - aws-checksums=0.1.17=hfd9eb17_5
  - aws-crt-cpp=0.24.7=h97e63c7_6
  - aws-sdk-cpp=1.11.182=h8beafcf_7
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311h06a4308_0
  - black=24.4.2=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.22.1=hd590300_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py311h06a4308_0
  - contourpy=1.2.0=py311h9547e67_0
  - cryptography=41.0.3=py311hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.4.1=h8ab8bb3_9
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.15.0=py_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py311h06a4308_0
  - fonttools=4.47.0=py311h459d7ec_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py311h459d7ec_1
  - fsspec=2023.10.0=pyhca7485f_0
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - huggingface_hub=0.18.0rc0=py_0
  - hypothesis=6.100.1=py311h06a4308_0
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.25.0=py311h92b7b1e_0
  - ipython=8.15.0=py311h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.2=py311h06a4308_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.19.2=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter_client=7.4.9=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - jupyter_server=1.23.4=py311h06a4308_0
  - jupyterlab_pygments=0.2.2=py311h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarrow=13.0.0=h475e73a_16_cpu
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcurl=8.4.0=hca28451_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libgomp=13.2.0=h807b86a_3
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgrpc=1.59.3=hd6c4280_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_0
  - libnpp=11.8.0.86=0
  - libnuma=2.0.16=h0b41bf4_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.06.02=h7a70373_0
  - librosa=0.10.1=pyhd8ed1ab_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.41.1=py311ha6695c7_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib-base=3.8.0=py311h54ef318_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mdurl=0.1.0=py311h06a4308_0
  - mistune=2.0.4=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.3=h59595ed_0
  - mpmath=1.3.0=py311h06a4308_0
  - msgpack-python=1.0.7=py311h9547e67_0
  - multidict=6.0.4=py311h459d7ec_1
  - multiprocess=0.70.15=py311h459d7ec_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=py311h06a4308_0
  - nbclassic=1.0.0=py311h06a4308_0
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.10.0=py311h06a4308_0
  - nbformat=5.9.2=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - notebook=6.5.4=py311h06a4308_1
  - notebook-shim=0.2.3=py311h06a4308_0
  - numba=0.58.1=py311h96b013e_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.2.0=hd590300_1
  - orc=1.9.2=h4b38347_0
  - packaging=23.1=py311h06a4308_0
  - pandas=2.1.3=py311h320fe9a_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py311h06a4308_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pooch=1.8.0=pyhd8ed1ab_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - protobuf=4.24.4=py311h46cbc50_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=13.0.0=py311h39c9aba_16_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyctcdecode=0.5.0=pyhd8ed1ab_0
  - pydantic=1.10.12=py311h5eee18b_1
  - pygments=2.15.1=py311h06a4308_1
  - pygtrie=2.5.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py311h06a4308_0
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py311h459d7ec_0
  - python_abi=3.11=2_cp311
  - pytorch=2.1.1=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=23.2.0=py311h6a678d5_0
  - rdma-core=28.9=h59595ed_1
  - re2=2023.06.02=h2873b5e_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - regex=2023.10.3=py311h459d7ec_0
  - requests=2.31.0=py311h06a4308_0
  - rich=13.7.1=py311h06a4308_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - s2n=1.3.56=h06160fa_0
  - sacremoses=master=py_0
  - safetensors=0.3.3=py311h46250e7_1
  - scikit-learn=1.3.2=py311hc009520_2
  - scipy=1.10.0=py311h8e6699e_2
  - send2trash=1.8.2=py311h06a4308_0
  - sentry-sdk=1.38.0=pyhd8ed1ab_0
  - setproctitle=1.3.3=py311h459d7ec_0
  - setuptools=68.0.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.2.0=py311h06a4308_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py311h06a4308_0
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.3.7=py311h1f0f07a_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py311h06a4308_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.14.1=py311h6640629_2
  - torchaudio=2.1.1=py311_cu118
  - torchtriton=2.1.0=py311
  - torchvision=0.16.1=py311_cu118
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py311h06a4308_0
  - transformers=4.35.2=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - ucx=1.15.0=h64cca9d_0
  - urllib3=1.26.18=py311h06a4308_0
  - wandb=0.16.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=0.58.0=py311h06a4308_4
  - wheel=0.41.2=py311h06a4308_0
  - xxhash=0.8.2=hd590300_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.2=py311h459d7ec_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - antlr4-python3-runtime==4.9.3
      - argparse==1.4.0
      - automat==22.10.0
      - babel==2.14.0
      - bibtexparser==2.0.0b7
      - buildtools==1.0.6
      - causal-conv1d==1.1.1
      - clldutils==3.22.1
      - colorlog==6.8.2
      - constantly==23.10.4
      - csvw==3.3.0
      - distance==0.1.3
      - dlinfo==1.2.1
      - docopt==0.6.2
      - edit-distance==1.0.6
      - einops==0.7.0
      - furl==2.1.3
      - g2p-en==2.1.0
      - greenlet==3.0.3
      - huggingface-hub==0.17.3
      - hydra-core==1.3.2
      - hyperlink==21.0.0
      - incremental==22.10.0
      - inflect==7.0.0
      - isodate==0.6.1
      - kenlm==0.2.0
      - language-tags==1.2.0
      - lxml==5.1.0
      - mamba-ssm==1.1.1
      - markdown==3.5.2
      - ninja==1.11.1.1
      - nltk==3.8.1
      - omegaconf==2.3.0
      - orderedmultidict==1.0.1
      - phonemizer==3.2.1
      - pylatexenc==2.10
      - rdflib==7.0.0
      - redo==2.0.4
      - rfc3986==1.5.0
      - segments==2.2.1
      - simplejson==3.19.2
      - sqlalchemy==2.0.25
      - tabulate==0.9.0
      - torcheval==0.0.7
      - twisted==23.10.0
      - uritemplate==4.1.1
      - zope-interface==6.1
